#!/usr/bin/env bash
set -e


echo "Linting code..."
prettier --single-quote --list-different 'src/**/*.jsx' 'test/*.test.js' 'test/*.test.jsx'
eslint --ext .jsx,.js src/
echo "Finished linting code."
